spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/renbin-1995/springcloudconfig/
          search-paths: renbin
          username:
          password:
      label: master


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8889/eureka/

server:
  port: 8888

